import React from 'react';
import {shallow} from 'enzyme';
import MainLayout from './MainLayout';
import Home from 'pages/Home/Home';
import Header from 'components/Header/Header';
import SidebarWrapper from 'components/Sidebar/Wrapper';
import Footer from 'components/Footer/Footer';
import Meals from 'pages/Meals/Meals';
import Weight from 'pages/Weight/Weight';
import Health from 'pages/Health/Health';
import Workout from 'pages/Workout/Workout';
import History from 'pages/History/History';
import Reminders from 'pages/Reminders/Reminders';
import Reports from 'pages/Reports/Reports';
import MyProducts from 'pages/MyProducts/MyProducts';
import Profile from 'pages/Profile/Profile';

it('renders the main layout', () => {
  const layout = shallow(<MainLayout />);
  expect(layout.find(Header)).toHaveLength(1);
  expect(layout.find(SidebarWrapper)).toHaveLength(1);
  expect(layout.find(Footer)).toHaveLength(1);
  expect(layout.find(Home)).toHaveLength(1);
  expect(layout.find(Meals)).toHaveLength(1);
  expect(layout.find(Weight)).toHaveLength(1);
  expect(layout.find(Health)).toHaveLength(1);
  expect(layout.find(Workout)).toHaveLength(1);
  expect(layout.find(History)).toHaveLength(1);
  expect(layout.find(Reminders)).toHaveLength(1);
  expect(layout.find(Reports)).toHaveLength(1);
  expect(layout.find(MyProducts)).toHaveLength(1);
  expect(layout.find(Profile)).toHaveLength(1);
});
